### ISSUE TITLE
Use Cases in English (Stefan Csomor, Advanced Concepts AG)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-lab-report#115] opened 2024-09-27 18:07 UTC
ch.fhir.ig.ch-lab-report#1.0.0-ballot /usecases-en.html

the resource graphic Resource Overview.svg is apparently missing or incorrect perhaps the space in the filename is a problem

Stefan Csomor, Advanced Concepts AG

**Comment by lpg-tech** [comment] 2024-11-03 09:34
Already resolved, duplicate of [#100](https://github.com/hl7ch/ch-lab-report/issues/100)

**Closed** 2024-11-05 06:13 UTC
Labels: documentation, duplicate, STU 1 Ballot, can be closed
